### PR TITLE
fix: compatibility with `webpack-dev-server`

### LINKED ISSUE #94: Deprecation warning log from webpack-dev-server.
We have a deprecation warning log too, coming from `webpack-dev-server`, [because of the usage of deprecated option `onBeforeSetupMiddleware` in the `error-overlay-webpack-plugin`](https://github.com/gregberge/error-overlay-webpack-plugin/blob/8aa4edf623e1a893933334367d10c17c525a62a0/src/index.js#L40)

Screenshot 2022-02-21 at 7 18 55 AM

This code should be migrated to the latest [`setupMiddlewares` option](https://webpack.js.org/configuration/dev-server/#devserversetupmiddlewares)
https://github.com/gregberge/error-overlay-webpack-plugin/blob/8aa4edf623e1a893933334367d10c17c525a62a0/src/index.js#L40

### PR DESCRIPTION
**Pull request by snitin315**
Fix https://github.com/gregberge/error-overlay-webpack-plugin/issues/94

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -22,7 +22,7 @@ class ErrorOverlayPlugin {
         compiler.options.devServer.host
       sockOptions.sockPath =
         compiler.options.devServer.client?.webSocketURL?.pathname ||
-        compiler.options.devServer.webSocketServer?.options.path ||
+        (compiler.options.devServer.webSocketServer === "object" && compiler.options.devServer.webSocketServer.options?.path) ||
```
Comment (snitin315) [inline src/index.js:25]: because `webSocketServer` can be a string as well. `devServer: { webSocketServer: "ws" }`

File: src/index.js [hunk 2]
```diff
@@ -37,11 +37,12 @@ class ErrorOverlayPlugin {
       if (devServerEnabled) {
         const originalOnBeforeSetupMiddleware =
           options.devServer.onBeforeSetupMiddleware
-        options.devServer.onBeforeSetupMiddleware = (devServer) => {
+          options.devServer.setupMiddlewares = (middlewares, devServer) => {
```
Comment (snitin315) [inline src/index.js:40]:
```suggestion
        options.devServer.setupMiddlewares = (middlewares, devServer) => {
```

**Comment by sibartlett** [comment]
Can this pull request be merged and released please?
